/**
 * Central icon registry.
 *
 * Data files reference icons by string name so they stay serialisable and
 * free of JSX. Previously each component kept its own local map, which meant
 * a new icon had to be registered in several places.
 */

import {
  Activity,
  ArrowRight,
  Award,
  BarChart3,
  BookOpen,
  Boxes,
  Brush,
  Building2,
  Calendar,
  Check,
  ClipboardList,
  Code2,
  Compass,
  CreditCard,
  Database,
  FileEdit,
  FileSearch,
  FileText,
  Gauge,
  Globe,
  Handshake,
  HeartPulse,
  Home,
  Layers,
  LayoutDashboard,
  LifeBuoy,
  Lightbulb,
  Link2,
  MapPin,
  Megaphone,
  MessageSquare,
  MonitorSmartphone,
  MousePointerClick,
  Paintbrush,
  PenTool,
  Plug,
  Rocket,
  Ruler,
  Scale,
  Search,
  Server,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Signpost,
  Sparkles,
  Store,
  Target,
  Terminal,
  TrendingUp,
  Users,
  Utensils,
  Wand2,
  Wrench,
  Zap,
} from "lucide-react";

export type IconName = keyof typeof iconMap;

export const iconMap = {
  activity: Activity,
  "arrow-right": ArrowRight,
  award: Award,
  "bar-chart": BarChart3,
  "book-open": BookOpen,
  boxes: Boxes,
  brush: Brush,
  building: Building2,
  calendar: Calendar,
  check: Check,
  clipboard: ClipboardList,
  code2: Code2,
  compass: Compass,
  "credit-card": CreditCard,
  database: Database,
  "file-edit": FileEdit,
  "file-search": FileSearch,
  "file-text": FileText,
  gauge: Gauge,
  globe: Globe,
  handshake: Handshake,
  "heart-pulse": HeartPulse,
  home: Home,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  lifebuoy: LifeBuoy,
  lightbulb: Lightbulb,
  link2: Link2,
  "map-pin": MapPin,
  megaphone: Megaphone,
  message: MessageSquare,
  monitor: MonitorSmartphone,
  "mouse-pointer": MousePointerClick,
  paintbrush: Paintbrush,
  "pen-tool": PenTool,
  plug: Plug,
  rocket: Rocket,
  ruler: Ruler,
  scale: Scale,
  search: Search,
  server: Server,
  settings: Settings,
  shield: ShieldCheck,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  signpost: Signpost,
  sparkles: Sparkles,
  store: Store,
  target: Target,
  terminal: Terminal,
  "trending-up": TrendingUp,
  users: Users,
  utensils: Utensils,
  wand: Wand2,
  wrench: Wrench,
  zap: Zap,
} as const;

/** Falls back to a neutral icon rather than crashing on an unknown or absent name. */
export function getIcon(name?: string) {
  if (!name) return Sparkles;
  return iconMap[name as IconName] ?? Sparkles;
}
